# -*- coding: utf-8 -*-
"""Iris_Flower_Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gwL-oAimeN1t0vnRUDnqy1RropFlxmVr
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

data = pd.read_csv('Iris.csv')
data.head()

data.describe()

data.info()

data.isnull().sum()

data.drop('Id', axis=1, inplace=True)

data.head()

sns.pairplot(data, hue="Species", size=3)

X = data.drop(columns=['Species'])
y = data['Species']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.neighbors import KNeighborsClassifier

# Create knn classifiers with value of k = 10
model_KNN = KNeighborsClassifier(n_neighbors=10)

model_KNN.fit(X_train, y_train)

y_pred = model_KNN.predict(X_test)

from sklearn.metrics import accuracy_score

def calculate_metrics(y_test, y_pred):
  knn_accuracy = accuracy_score(y_test, y_pred)
  print(f"Accuracy of KNN Classifier: {knn_accuracy}")

calculate_metrics(y_test, y_pred)



def user_input():
  SepalLengthCm = float(input('Enter Sepal Length (cm): '))
  SepalWidthCm = float(input('Enter Sepal Width (cm): '))
  PetalLengthCm = float(input('Enter Petal Length (cm): '))
  PetalWidthCm = float(input('Enter Petal Width (cm): '))

  return [[SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm]]

user_data = user_input()

user_input_prediction = model_KNN.predict(user_data)

print("Iris Species: ", user_input_prediction[0])

